### ISSUE TITLE
[Doc] The Docs should mention that a custom layout's name cannot contain 'layout' or it won't be found in the registery

### ISSUE THREAD

**Issue by EkiGui** [TypedProject/logger#15]
Hi,

I spent quite some time looking around why my shiny custom layout, called *customLayout*, was not found by my logger. Turns out it was caused by this line:

https://github.com/TypedProject/ts-log-debug/blob/20ca9a2bdea739a0f20f1b443a0727907019bfab/src/layouts/class/Layouts.ts#L10 

As `layout` is trimmed from the name, it was not found in the registry. I don't understand the necessity for this replacement, nor the strange `colored` hard coded name (causing a mysterious `colored layout doesn't exists` error message, no matter layout's name), but I guess mentioning this in the docs could help some folks.

I'm using this library inside a TS.ED project. I **love** your framework, thanks for the awesome work 😉

**Comment by Romakita** [comment]
@EkiGui Thanks for you message :)
My apologize for the wasted time. In fact, in large part of this code are inspired from log4js. Certains errors message are also obscurs for me ;)

I keep your issue open and I'll try to improve the code and documentation.

**Comment by cspotcode** [comment]
Any reason to use a registry instead of just passing an object that implements the correct interface?  Instead of passing `layout: "myLaout"` I'd rather just pass `layout: new MyLayout(opts)`

**Comment by Romakita** [comment]
Good question. A large part of the mentioned code are inspired from log4js. It shouldn’t a big deal to improve this part, to support the name config or/and your solution.

A PR is welcome. I’ll try to work on next week and fix the documentation :)
