### ISSUE TITLE
Date rolling log file

### ISSUE THREAD

**Issue by paaragon** [TypedProject/logger#17]
## Informations

Type | Version
---|---
Question | ^4.0.1

****

## Description
In the "Features" section is specified that the rolling based on date is available but I cannot find information about how to configure it.

¿Any help?

Thank you a lot

**Comment by Romakita** [comment]
What do you mean by "the rolling based on date"?

**Comment by paaragon** [comment]
Hello!

Is on the README.md

![E34A9754-5847-4E14-8C7F-607CD6ABC9DD](https://user-images.githubusercontent.com/7396204/73100019-fca38400-3eec-11ea-8d32-57c48e630b06.jpeg)

**Comment by Romakita** [comment]
Ho yes exactly. I’ll check where is the feature description is located

**Comment by Romakita** [comment]
Ok my bad. This appender isn’t implemented.

**Comment by paaragon** [comment]
I have just create a PR with the new feature. If you think it doesn't seem good enough tell me and I'll try to improve it

**Comment by paaragon** [comment]
I saw the pull request was accepted. Thank's for that!

This feature will be available by npm?

**Comment by Romakita** [comment]
Yes the feature is available on npm :)

**Comment by paaragon** [comment]
Thank you so much!
