### ISSUE TITLE
Docs mention .push, but LoggerAppenders has only .set

### ISSUE THREAD

**Issue by PAStheLoD** [TypedProject/logger#19]
## Informations

Bug / 5.4.1 (and current master)

****

## Description
There's a discrepancy between the docs (both readme files, the on at the root of the repo and the one in the packages/logger/) and the code. The docs say that logger.appenders has a "push" method, but the class in logger/packages/logger/src/logger/class/LoggerAppenders.ts file has no such method.

**Comment by Romakita** [comment]
Ho sorry. Yes the right is .set()

**Comment by Romakita** [comment]
I’ll fix the docs asap

**Comment by Romakita** [comment]
fixed
