### ISSUE TITLE
Docs mention appender `dateFile` but doesn't exist

### ISSUE THREAD

**Issue by SyntleLmao** [TypedProject/logger#20]
## Informations

Type | Version
---|---
Question | 5.4.1

****

## Description
I tried to use the `dateFile` appender as the docs showed but got the error below.

## Error
UNKNOW_APPENDER: Appender dateFile doesn't exists. Check your configuration:
{"type":"dateFile","filename":"log.log","pattern":".dd-MM-yyyy","compress":true}

**Comment by Romakita** [comment]
Hello @SyntleLmao 
It's a typo. Here the right example:

````
logger.appenders
  .set('file', {
    type: 'file',
    filename: `${__dirname}/../logs/myfile.log`,
    pattern: '.yyyy-MM-dd'
 });
```
I'll fix the documentation :)

**Comment by SyntleLmao** [comment]
Just tested it, that works, thank you.
