### ISSUE TITLE
Log file random characters before and after timestamp & logger name

### ISSUE THREAD

**Issue by SyntleLmao** [TypedProject/logger#21]
## Informations

Type | Version
---|---
Bug? | 5.4.1

****

## Description
When I log anything I always get random characters as shown in this line from my log file:
```[31m[2020-04-01T00:29:54.828] [ERROR] [Client] - [39mUncaught Promise Rejection:```
most of the time it starts with `[32m` instead of `[31m`

## My Config
```
const Logger = new Logger("Client");

Logger.appenders.set("logs", {
    type: 'file',
    filename: `${__dirname}/../logs/RT.log`,
    pattern: '.dd-MM-yyyy',
    compress: true
});```

**Comment by Romakita** [comment]
Hello @SyntleLmao 
To remove colored symbol you have to change the layout:

```typescript
const Logger = new Logger("Client");

Logger.appenders.set("logs", {
    type: 'file',
    layout: {type: "basic"}// or layout: {type: "json"}
    filename: `${__dirname}/../logs/RT.log`,
    pattern: '.dd-MM-yyyy',
    compress: true
});
```
It preferable to use `json` layout if your goals is to parse the log with logstash ;)
See you
Romain

**Comment by SyntleLmao** [comment]
Thanks a lot
