### ISSUE TITLE
logger.shutdown().then() isn’t resolved as expected

### ISSUE THREAD

**Issue by Syntle** [TypedProject/logger#22]
## Informations

Type | Version
---|---
Bug | 5.4.1

****

## Description
The below code does not return anything, this is how it was written in the docs.
```js
process.on('SIGINT', () => {
    Logger.shutdown().then(() => console.log('Shutdown Logger'));
});
```

**Comment by Romakita** [comment]
Hello @SyntleLmao 
Yes it's a typo. Shutdown is only available on the logger instance ($log or your own logger instance):
```typescript
process.on('SIGINT', () => {
    $log.shutdown().then(() => console.log('Shutdown Logger'));
     // or your instance logger
   $myLogger.shutdown().then(() => console.log('Shutdown Logger'));
});
```

See you
Romain

**Comment by SyntleLmao** [comment]
I did get the information from `getting started`.

I tried `$Logger` but I'm getting a `Cannot find name` error.

Could you explain how I can get it to work?

**Comment by Romakita** [comment]
Hello @SyntleLmao 

You have to adapt the example code to your context xD. If you have created a new logger instance, use this variable to shutdown logger.

I have that on the getting started:
```typescript
import {Logger} from "@tsed/logger";

const myLogger = new Logger("loggerName");
myLogger
  .shutdown()
  .then(() => {
     console.log("Complete")
  });
```
The example is clear and works. So what is your problem, exactly and what don’t you understand ?  :)
See you
Romain

**Comment by SyntleLmao** [comment]
The problem is I used the getting started example from the beginning and it didn't return anything, that's why I opened an issue.

**Comment by Romakita** [comment]
Sorry. I think, i don’t understand. What do you mean by return anything? What did you expect?

**Comment by Romakita** [comment]
Ok you mean the promise is resolved. Right?

**Comment by SyntleLmao** [comment]
I expect it to console.log something.

**Comment by Romakita** [comment]
Ok so the problem is the promise isn’t resolved as expected. Now is clear.

**Comment by Romakita** [comment]
Hum the code works. The problem is probably related with the SIGINT event. The stdout is probably closed when the promise is resolved.

Try to shutdown the logger outside the SIGINT. If the log appear, it's a problem just with the SIGINT and promise.

See you,
Romain
