### ISSUE TITLE
ISO8601 with TZ offset issue via date-format 2.x bug

### ISSUE THREAD

**Issue by PAStheLoD** [TypedProject/logger#26]
## Information

Type | Version
---|---
Bug | master

****

## Description
Logger uses a buggy version of date-format, see https://github.com/nomiddlename/date-format/issues/14 .. date-format 3.0 fixed this.

## Todos

- [ ] Check for potential compatibility issues
- [ ] Upgrade date-format dependency to 3.x

**Comment by Romakita** [comment]
Hello @PAStheLoD 

Thank for your issue :). Is possible to make a PR? I’m on vaccation but I can validate PR ;)

See you
Romain
