### ISSUE TITLE
Usage of ts-debug-logger in Web

### ISSUE THREAD

**Issue by am0wa** [TypedProject/logger#4]
## Informations

Type | Version
---|---
Improvement |  ^4.0.4

****

## Description
The overall Goal is to **Usage of *ts-debug-logger* in Web Applications**. Not only in Node Env.

## Todos

Please Remove **"stdout"** & **"stderr"** appenders, or provide the way to override those during creation of Default logger. Because creation of default Logger with those appenders causes the exceptions in Web.

```
var $log = new Logger_1.Logger("default");
exports.$log = $log;
$log.appenders
    .set("stdout", { type: "stdout", levels: ["info", "debug"] })
    .set("stderr", { type: "stderr", levels: ["trace", "fatal", "error", "warn"] });
exports.default = {
    $log: $log
};
```

- [ ] Error Example

**TypeError: process.stdout is undefined**
```
StdoutAppender
./node_modules/ts-log-debug/lib/appenders/components/StdoutAppender.js:35

  32 | tslib_1.__extends(StdoutAppender, _super);
  33 | function StdoutAppender() {
  34 |     var _this = _super !== null && _super.apply(this, arguments) || this;
> 35 |     _this.log = process.stdout.write.bind(process.stdout);
  36 |     return _this;
  37 | }
  38 | StdoutAppender.prototype.write = function (loggingEvent) {
```

**Comment by Romakita** [comment]
Hello @andrewmur,
In the documentation here https://romakita.github.io/ts-log-debug/#/appenders/console describe how you can use console Appender instead of Stdout.

Here an example:
```javascript
var $log = new Logger_1.Logger("default");
exports.$log = $log;
$log.appenders
    .set("console", { type: "console", levels: ["info", "debug"] })
    .set("console", { type: "console", levels: ["trace", "fatal", "error", "warn"] });
exports.default = {
    $log: $log
};
```

Note: This library ins't design to be used in a front-end application. I don't want support this part. Excepted if someone help me to maintain the library ;)

See you,
Romain
